# Generated by Django 2.2.9 on 2021-07-17 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='current_users',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
